from django.urls import path, reverse_lazy
from django.utils.translation import gettext_lazy as _
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name='home'),
    path('custom-login/',
         auth_views.LoginView.as_view(template_name='pages/login.html'),
         name='custom_login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),
    path('subir-publicacion/', views.feed, name='subir_publicacion'),
    path('post/<int:post_id>/delete/', views.delete_post, name='delete_post'),
    path('post/new/', views.create_post, name='create_post'),
    path('story/upload/', views.upload_story, name='upload_story'),
    path('post/<int:post_id>/like/', views.like_post, name='like_post'),
    path('post/<int:post_id>/share/', views.share_post, name='share_post'),
    path('post/<int:post_id>/comment/', views.comment_post, name='comment_post'),
    path('post/<int:post_id>/comments/', views.load_comments, name='load_comments'),
    path('comment/<int:comment_id>/replies/', views.load_replies, name='load_replies'),
    path('comment/<int:comment_id>/like/', views.like_comment, name='like_comment'),
    path('comment/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path("settings/delete/", views.delete_account, name="account_delete"),
    path(
        "settings/password/",
        auth_views.PasswordChangeView.as_view(
            template_name="accounts/password_change.html",
            success_url=reverse_lazy("edit_profile"),
        ),
        name="password_change",
    ),
    path("profile/edit/privacy/", views.edit_profile, name="settings_privacy"),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('friend-requests/', views.friend_requests_view, name='friend_requests'),
    path('friend-requests/accept/<int:req_id>/', views.accept_friend_request, name='accept_friend_request'),
    path('friend-requests/reject/<int:req_id>/', views.reject_friend_request, name='reject_friend_request'),
    path('send-friend-request/', views.send_friend_request, name='send_friend_request'),
    path('update-bubble-color/', views.update_bubble_color, name='update_bubble_color'),
    path(_('user-search/'), views.user_search_page, name='user_search_page'),
    path('buscador/', views.buscador_page, name='buscador_page'),
    path("api/search-users/", views.search_users, name="search_users"),
    path("api/search-communities/", views.search_communities, name="search_communities"),
    path("api/location-search/", views.search_locations, name="location_search"),
    path("api/stories/", views.api_stories, name="api_stories"),
    path("api/stories/upload/", views.api_upload_story, name="api_upload_story"),
    path('community/<str:username>/follow/', views.follow_community, name='follow_community'),
    path('community/<str:username>/unfollow/', views.unfollow_community, name='unfollow_community'),
    path('block-user/<str:username>/', views.block_user, name='block_user'),
    path('hide-stories/<str:username>/', views.hide_stories, name='hide_stories'),
    path('settings/hidden-stories/', views.hidden_stories_list, name='hidden_stories_list'),
    path('settings/hidden-stories/unhide/<str:username>/', views.unhide_stories, name='unhide_stories'),
    path('settings/blocked-users/', views.blocked_users_list, name='blocked_users_list'),
    path('settings/blocked-users/unblock/<str:username>/', views.unblock_user, name='unblock_user'),
    path('chats/', views.chat_list, name='chat_list'),
    path('chat/<int:chat_id>/', views.chat_detail, name='chat_detail'),
    path('start-chat/<int:user_id>/', views.start_chat, name='start_chat'),
    path('chat/<int:chat_id>/messages/', views.load_messages, name='load_messages'),
    path('story/<int:story_id>/view/', views.view_story, name='view_story'),
    path('story/<int:story_id>/viewers/', views.story_viewers, name='story_viewers'),
    path('story/<int:story_id>/delete/', views.delete_story, name='delete_story'),
    path('story/<int:story_id>/reply/', views.reply_story, name='reply_story'),
    path('notifications/', views.notifications_view, name='notifications'),
    path('mark-notification-read/<int:notification_id>/', views.mark_notification_read, name='mark_notification_read'),
    path('api/notifications-count/', views.get_notifications_count, name='notifications_count'),
    path('api/friends/', views.friends_list_partial, name='friends_list_partial'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
    path('404/', views.test_404_view)
]
