from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('subir-publicacion/', views.feed, name='subir_publicacion'),
    path('post/<int:post_id>/delete/', views.delete_post, name='delete_post'),
    path('post/new/', views.create_post, name='create_post'),
    path('story/upload/', views.upload_story, name='upload_story'),
    path('post/<int:post_id>/like/', views.like_post, name='like_post'),
    path('post/<int:post_id>/share/', views.share_post, name='share_post'),
    path('post/<int:post_id>/comment/', views.comment_post, name='comment_post'),
    path('post/<int:post_id>/comments/', views.load_comments, name='load_comments'),
    path('comment/<int:comment_id>/replies/', views.load_replies, name='load_replies'),
    path('comment/<int:comment_id>/like/', views.like_comment, name='like_comment'),
    path('comment/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('friend-requests/', views.friend_requests_view, name='friend_requests'),
    path('friend-requests/accept/<int:req_id>/', views.accept_friend_request, name='accept_friend_request'),
    path('friend-requests/reject/<int:req_id>/', views.reject_friend_request, name='reject_friend_request'),
    path('send-friend-request/', views.send_friend_request, name='send_friend_request'),
    path('update-bubble-color/', views.update_bubble_color, name='update_bubble_color'),
    path("api/search-users/", views.search_users, name="search_users"),
    path('follow/<str:username>/', views.follow_user, name='follow'),
    path('unfollow/<str:username>/', views.unfollow_user, name='unfollow'),
    path('cancel-request/<str:username>/', views.cancel_follow_request, name='cancel_request'),
    path('remove-follower/<str:username>/', views.remove_follower, name='remove_follower'),
    path('block-user/<str:username>/', views.block_user, name='block_user'),
    path('hide-stories/<str:username>/', views.hide_stories, name='hide_stories'),
    path('settings/hidden-stories/', views.hidden_stories_list, name='hidden_stories_list'),
    path('settings/hidden-stories/unhide/<str:username>/', views.unhide_stories, name='unhide_stories'),
    path('chats/', views.chat_list, name='chat_list'),
    path('chat/<int:chat_id>/', views.chat_detail, name='chat_detail'),
    path('start-chat/<int:user_id>/', views.start_chat, name='start_chat'),
    path('chat/<int:chat_id>/messages/', views.load_messages, name='load_messages'),
    path('story/<int:story_id>/view/', views.view_story, name='view_story'),
    path('story/<int:story_id>/viewers/', views.story_viewers, name='story_viewers'),
    path('story/<int:story_id>/delete/', views.delete_story, name='delete_story'),
    path('story/<int:story_id>/reply/', views.reply_story, name='reply_story'),
    path('notifications/', views.notifications_view, name='notifications'),
    path('mark-notification-read/<int:notification_id>/', views.mark_notification_read, name='mark_notification_read'),
    path('api/notifications-count/', views.get_notifications_count, name='notifications_count'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
    path('404/', views.test_404_view)
]
