name: spoonapp_frontend
version: 0.1.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.0
  go_router: ^7.1.1
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
