# Generated by Django 5.2.3 on 2025-06-14

from django.db import migrations


def create_categories(apps, schema_editor):
    PostCategory = apps.get_model('social', 'PostCategory')
    categories = [
        'Verduras',
        'Carne',
        'Pasta',
        'Pescado',
        'Primer plato',
        'Segundo plato',
        'Postres',
    ]
    for name in categories:
        PostCategory.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_postcomment_dislikes_postcomment_likes_and_more'),
    ]

    operations = [
        migrations.RunPython(create_categories, migrations.RunPython.noop),
    ]

