# Generated by Django 5.2.3 on 2025-06-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_merge_20250613_1629'),
        ('social', '0008_merge_20250613_1633'),
    ]

    operations = [
    ]
