# Generated by Django 5.2.3 on 2025-06-16 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_merge_20250616_1111'),
        ('social', '0010_merge_20250616_1213'),
    ]

    operations = [
    ]
