# Generated by Django 5.2.3 on 2025-06-16 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0017_merge_20250616_1701"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="story",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="social.story",
            ),
        ),
    ]
