# Generated by Django 5.2.3 on 2025-06-17 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_merge_20250616_1658'),
        ('social', '0018_message_story'),
    ]

    operations = [
    ]
