# Generated by Django 5.2.3 on 2025-06-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0022_profile_bio_profile_gender_profile_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="story",
            name="media_file",
        ),
        migrations.AddField(
            model_name="post",
            name="image_mime",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_picture_mime",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="story",
            name="media_data",
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AddField(
            model_name="story",
            name="media_mime",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
