# Generated by Django 5.2.3 on 2025-06-13 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoryComment',
        ),
    ]
