# Generated by Django 5.2.3 on 2025-06-13 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_alter_profile_profile_picture_friendrequest'),
        ('social', '0007_update_categories'),
    ]

    operations = [
    ]
