# Generated by Django 5.2.3 on 2025-06-16 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_merge_20250613_1646'),
        ('social', '0009_merge_20250616_1131'),
    ]

    operations = [
    ]
