# Generated by Django 5.2.3 on 2025-06-16 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_chat_alter_message_receiver_alter_message_sender_and_more'),
        ('social', '0012_profile_last_seen'),
    ]

    operations = [
    ]
