# Generated by Django 5.2.3 on 2025-06-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0014_alter_message_options_notification"),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='image',
            new_name='media_file',
        ),
        migrations.AlterField(
            model_name='story',
            name='media_file',
            field=models.FileField(upload_to='stories/'),
        ),
    ]
