# Generated by Django 5.2.3 on 2025-06-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_alter_message_options_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
