# Generated by Django 5.2.3 on 2025-06-16 15:49

import social.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0015_story_media_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="expires_at",
            field=models.DateTimeField(default=social.models.default_expiration),
        ),
    ]
