# Generated by Django 5.2.3 on 2025-06-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_postcategory_slug'),
        ('social', '0016_alter_story_expires_at'),
    ]

    operations = [
    ]
