# Generated by Django 5.2.3 on 2025-06-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0023_remove_story_media_file_post_image_mime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bubble_color",
            field=models.CharField(default="#ff0000", max_length=7),
        ),
    ]
