# Generated by Django 5.2.4 on 2025-07-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0029_add_clips_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="video",
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="video_mime",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
